-- MySQL Script generated by MySQL Workbench
-- mar 12 jul 2022 12:19:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portafolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portafolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portafolio` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `portafolio` ;

-- -----------------------------------------------------
-- Table `portafolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_postal` SMALLINT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(200) NULL,
  `foto_perfil_url` VARCHAR(100) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portafolio`.`tipo_empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`tipo_empleo` (
  `idtipo_empleo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_empleo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portafolio`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`experiencia_laboral` (
  `idexperiencia` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `descripcion` TEXT(200) NULL,
  `idpersona` INT NOT NULL,
  `idtipo_empleo` INT NOT NULL,
  PRIMARY KEY (`idexperiencia`, `idpersona`, `idtipo_empleo`),
  INDEX `fk_experiencia_laboral_persona_idx` (`idpersona` ASC) VISIBLE,
  INDEX `fk_experiencia_laboral_tipo_empleo1_idx` (`idtipo_empleo` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_laboral_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `portafolio`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_tipo_empleo1`
    FOREIGN KEY (`idtipo_empleo`)
    REFERENCES `portafolio`.`tipo_empleo` (`idtipo_empleo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `portafolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`proyectos` (
  `idproyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT(200) NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `url_proyecto` VARCHAR(100) NULL,
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`idproyecto`, `idpersona`),
  INDEX `fk_proyectos_persona1_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `portafolio`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `portafolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`educacion` (
  `ideducacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `descripcion` TEXT(200) NULL,
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`ideducacion`, `idpersona`),
  INDEX `fk_educacion_persona1_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `portafolio`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `portafolio`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portafolio`.`skills` (
  `idskill` INT NOT NULL AUTO_INCREMENT,
  `skill` VARCHAR(20) NOT NULL,
  `idpersona` INT NOT NULL,
  PRIMARY KEY (`idskill`, `idpersona`),
  INDEX `fk_skills_persona1_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `fk_skills_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `portafolio`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
